"""add_oauth_and_verification_fields

Revision ID: 3713d2479142
Revises: 733d365d054b
Create Date: 2026-08-12 08:09:45.110097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3713d2479142'
down_revision: Union[str, Sequence[str], None] = '733d365d054b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_user_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('student_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('employee_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('designation', sa.String(), nullable=True))
    op.add_column('users', sa.Column('course', sa.String(), nullable=True))
    op.add_column('users', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('semester', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('document_url', sa.String(), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_auth_user_id'), 'users', ['auth_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_auth_user_id'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'document_url')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'semester')
    op.drop_column('users', 'year')
    op.drop_column('users', 'course')
    op.drop_column('users', 'designation')
    op.drop_column('users', 'employee_id')
    op.drop_column('users', 'student_id')
    op.drop_column('users', 'auth_user_id')
    # ### end Alembic commands ###
