"""add_verification_and_audit

Revision ID: 733d365d054b
Revises: 6655a5ba06f8
Create Date: 2026-08-09 14:01:06.850431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '733d365d054b'
down_revision: Union[str, Sequence[str], None] = '6655a5ba06f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type userstatus in PostgreSQL
    userstatus = sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'SUSPENDED', name='userstatus')
    userstatus.create(op.get_bind(), checkfirst=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.add_column('users', sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'SUSPENDED', name='userstatus'), nullable=False, server_default='PENDING'))
    op.add_column('users', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('verified_by_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('verification_reason', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['verified_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'verification_reason')
    op.drop_column('users', 'verified_by_id')
    op.drop_column('users', 'verified_at')
    op.drop_column('users', 'status')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    
    # Drop enum type
    userstatus = sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'SUSPENDED', name='userstatus')
    userstatus.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
